= Codeína

A tool for generating beautiful API documentation for Clojure and ClojureScript.

This is a https://github.com/weavejester/codox[Codox] fork with various structural changes and a new look.

== Quick Start

Include the following plugin in your project.clj file or your global profile:

[source,clojure]
----
:plugins [[funcool/codeina "0.2.0"
           :exclusions [org.clojure/clojure]]]
----

Add the initial configuration, specifying the location of your sources and the language:

[source,clojure]
----
:codeina {:sources ["src"]
          :reader  :clojure}
----

And run the `doc` lein subcommand:

[source,shell]
----
$ lein doc
Generated HTML docs in /path/to/your/project/doc
----

== Configuration

This is a complete example that uses all available options:

[source, clojure]
----
:codeina {:sources ["src"]
          :exclude [cats.monad.continuation
                    cats.monad.reader
                    cats.monad.writer]
          :reader :clojure
          :target "doc/dist/latest/api"
          :src-uri "http://github.com/funcool/cats/blob/master/"
          :src-uri-prefix "#L"}
----

And this is a detailed explanation of possible options:

* `:sources` ->  a vector of paths that should be analyzed for extracting the docstrings.
* `:reader` -> a reader that should be used. Can be `:clojure` or `:clojurescript`.
* `:exclude` -> a vector of namespace symbols that should be excluded.
* `:target` -> the directory where the documentation should be generated.
* `:src-uri` -> the base URI for the source code location.
* `:src-uri-prefix` -> additional URI prefix.


In addition to those configuration options, _codeina_ interprets the metadata attached
to vars in the code. You can exclude specific vars from the documentation
by adding `^:no-doc` to their metadata, or to an entire namespace.

Also, you can use `^:deprecated` to visually mark in the documentation that
a var is deprecated.


== Examples

- https://funcool.github.io/catacumba/latest/api/
- https://funcool.github.io/cats/latest/api/
